### PR TITLE
Support vexpress

### PR DESCRIPTION
**Pull request by xiane**
To support vexpress, modifies source codes
- Fix uart code to support vexpress
- Configure and separate build scripts
- Add board configuration files, memory linker scripts and u-boot booting commands
- Modify Makefiles
- Add manual to support vexpress

### CODE REVIEW

**Comment by kesl** [comment]
Can one of the admins verify this patch?

**Comment by xiane** [comment]
Because building script files are moved other directory, verifying will not be worked

**Comment by Wonseok** [comment]
ok to test.

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/232/

**Pull request closed without merging**
