### PR TITLE
Added comments for doxygen style

### PR DESCRIPTION
**Pull request by kim6515516**
Added comments as doxygen style into vdev.[ch], trcp.[ch], vdev_gicd.[ch] vdev_timer.[ch]

Removed unused function or unnecessary code.
int register_vdev(void); in vdev.h

### CODE REVIEW

**Comment by kesl** [comment]
Can one of the admins verify this patch?

**Comment by Wonseok** [comment]
Could you please remove inkyu's commit? and make your commit clean.

**Comment by Wonseok** [comment]
We already knew this commit to add doxygen comment. So you don't need to write doxygen.

**Comment by Wonseok** [comment]
Added comments as doxygen style into vdev.[ch], trcp.[ch], vdev_gicd.[ch] vdev_timer.[ch]
not trcp, trap. 
Please read your comments carefully before pull request.

**Pull request closed without merging**
