### PR TITLE
change uart_print to printh

### PR DESCRIPTION
**Pull request by mijong**
1. change uart_print to printh 
2. add 64 bit printh function (use printh ("%ld",val))

### CODE REVIEW

**Comment by kesl** [comment]
Can one of the admins verify this patch?

**Comment by Wonseok** [comment]
ok to test

**Comment by joohyun0115** [comment]
ok to test

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/226/

**Comment by joohyun0115** [comment]
License check failed!

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/227/

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/228/

**Comment by mijong** [comment]
close

**Pull request closed without merging**
