### PR TITLE
[GuestLoader]: Add autoboot for guestloader

### PR DESCRIPTION
**Pull request by in1004kyu**
1. Add CLI (command.*)
2. Add autoboot (main.c)
3. Fix guestloader's memory map(Add sp for system/user mode)
4. Add writel/readl function in asm_io.h

CLI is worked on RTSM. Arndale is not supproted.

### CODE REVIEW

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/148/

**Comment by joohyun0115** [comment]
Look so good!

**Comment by joohyun0115** [comment]
retest this please

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/149/

**Comment by in1004kyu** [comment]
¤Ð¤Ð
2014. 3. 20. ¿ÀÈÄ 8:28¿¡ "kesl" notifications@github.com´ÔÀÌ ÀÛ¼º:

**Comment by in1004kyu** [comment]
retest this please

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/150/

**Pull request closed without merging**
