### PR TITLE
[versatile] support versatile express

### PR DESCRIPTION
**Pull request by xiane**
support versatile express
- modify uart
- add conditional command : Makefile and linker script
- change the core frequency
- create build script and u-boot command
- modify guest loader 's address jump macro

### CODE REVIEW

**Comment by kesl** [comment]
Can one of the admins verify this patch?

**Comment by joohyun0115** [comment]
ok to test

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/259/

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/260/

**Pull request closed without merging**
