### PR TITLE
[Android] : 1. Refactory for guestloader (consolidation code and removed...

### PR DESCRIPTION
**Pull request by in1004kyu**
... magic number)
1. Added atags of initrd for android booting at rtsm.
2. Modified zImage's load address 0x40000000 at arndale board for mmc supported.
3. Modified gestloader. Now Guest loader do not need include guest image. Guest loader operates similarly with bootloader. It loaded guest image from sd card. Now Linux kernel uses ram over 256MB. It's on arndale board.
4. Hypervisor's offset is modified (0xA0000000 ->  0xB0000000) by multi-core team. I modified it in advance.
5. Added mct timer initialization at arndale board.
6. Now Hypervisor can support android booting at rtsm and arndale board.
7. Updated README about Flash to arndale board and booting android at rtsm.

### CODE REVIEW

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/243/

**Comment by in1004kyu** [comment]
Android booting can be supported when @kim6515516's commit is applied

**Comment by in1004kyu** [comment]
retest this please

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/244/

**Comment by Wonseok** [comment]
Why do you use refactory here? You don't need to use refactory because it is not an infinitive of refactorying. Please check an word before you use. 
Please see this page: http://en.wiktionary.org/wiki/refactoring

**Pull request closed without merging**
