### PR TITLE
Emulated trapped mcr and mrc instructions for RTSM.

### PR DESCRIPTION
**Pull request by Wonseok**
Encoded ISS field for mcr and mrc instructions when the instructions called from guest OS.
TODO(Wonseok): Adds this feature to ARNDALE BOARD.

Encoded result in Hyp mode:
Trapped WFI or WFE instruction: 07e00000
32-bit ARM instruction
WFI trapped.
Trapped SMC instruction: 4e000000
Trapped MCR or MRC access to CP15: 0fe00460
MCR p15, 0, Rt3, c1, c0, 0
Trapped MCR or MRC access to CP15: 0fe20460
MCR p15, 0, Rt3, c1, c0, 1
Trapped MCR or MRC access to CP15: 0fe20461
MRC p15, 0, Rt3, c1, c0, 1

### CODE REVIEW

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/161/

**Comment by joohyun0115** [comment]
retest this please

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/162/

**Comment by joohyun0115** [comment]
retest this please

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/163/

**Comment by joohyun0115** [comment]
retest this please

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/164/

**Comment by joohyun0115** [comment]
retest this please

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/171/

**Pull request closed without merging**
