### PR TITLE
Added initial project for PC version of khypervisor.

### PR DESCRIPTION
**Pull request by Beomjun**
It includes initial files(main, Makefile, config-default.mk and more) and PC version of timer which is developing.

### CODE REVIEW

**Comment by kesl** [comment]
Can one of the admins verify this patch?

**Comment by Beomjun** [comment]
ok to test

**Comment by joohyun0115** [comment]
ok to test

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/212/

**Comment by joohyun0115** [comment]
Hmm. CI server has some problem.

**Comment by Beomjun** [comment]
Installation test makes problem.. I just checked coding style.

**Comment by Beomjun** [comment]
I will close this pull request myself.

**Comment by joohyun0115** [comment]
retest this please

**Comment by joohyun0115** [comment]
retest this please

**Pull request closed without merging**
