### PR TITLE
[GuestLoader]: Added autoboot for guestloader.

### PR DESCRIPTION
**Pull request by in1004kyu**
guestloader's squeance diagram : http://keslproject.iptime.org/mediawiki/images/0/05/Guestloader.jpg
1. Added CLI (command.*)
2. Added autoboot (main.c)
3. Fixed guestloader's memory map(Add sp for system/user mode)
4. Added writel/readl function in asm_io.h
5. Refactoring code.
6. Remove common/guest/command directory

CLI is worked on RTSM. Arndale is not supproted.

### CODE REVIEW

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/196/

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/197/

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/198/

**Comment by joohyun0115** [comment]
Look so good!

**Pull request merged**
