### PR TITLE
[versatile] Support versatile express

### PR DESCRIPTION
**Pull request by xiane**
support versatile express

modified uart code
Added conditional command in Makefile and linker script
Changed the core frequency
Create build script and u-boot command for bmguest and linux guest
Modified guest loader 's address jump macro

### CODE REVIEW

**Comment by kesl** [comment]
Can one of the admins verify this patch?

**Comment by joohyun0115** [comment]
ok to test

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/261/

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/262/

**Comment by Wonseok** [comment]
고상철.. 내가 말한거 빠진거 있으니깐 다시 보고
Frequency 관련해서 그따위로 숫자 쓰면 누가 알아 그게 변환되서 어떤 FREQ로 동작하는지 적으라고.....

생각들 좀 하고 살아... 말한대로만 하지 말고 니들이 기계냐?

Thanks,
Wonseok.

2014-10-01 17:44 GMT+09:00 kesl notifications@github.com:

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/263/

**Pull request closed without merging**
