### PR TITLE
Added comments and fixed wrong defined mask.

### PR DESCRIPTION
**Pull request by xiane**
Added comments to source files.
- lpae.h, lpae.c, mm.c, mm.h, smp.h, vmm.h and vmm.c.

Fixed TTBL level 1 mask bit.
- In lpae.c file. TTBL_L2_OUTADDR_MASK
  - 0x000000FFEC000000ULL -> 0x000000FFC0000000ULL

### CODE REVIEW

**Comment by kesl** [comment]
Can one of the admins verify this patch?

**Comment by joohyun0115** [comment]
ok to test

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/160/

**Comment by joohyun0115** [comment]
Server has some problem.

**Comment by Wonseok** [comment]
상철이가 테스트 안하고 돌린거예요. 우선 지켜봅시다.

Thanks,
Wonseok.

2014-03-21 19:00 GMT+09:00 joohyun0115 notifications@github.com:

**Comment by xiane** [comment]
Self test is succeeded.

**Comment by joohyun0115** [comment]
I know. I will check.

**Comment by in1004kyu** [comment]
retest this please

**Pull request closed without merging**
