### PR TITLE
[GUEST] Move receiving vtimer interrupt code to c_start.c

### PR DESCRIPTION
**Pull request by in1004kyu**
This patch separates virtual timer from gic.

### CODE REVIEW

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/141/

**Comment by in1004kyu** [comment]
retest this please

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/142/

**Comment by Wonseok** [comment]
TEST.

**Comment by Wonseok** [comment]
이거 주석 별로라서 닫아버릴리고 했는데 ㅋㅋ

**Pull request merged**
