### PR TITLE
[GuestLoader]: Add autoboot for guestloader

### PR DESCRIPTION
**Pull request by in1004kyu**
1. Add CLI (command.*)
2. Add autoboot (main.c)
3. Fix guestloader's memory map(Add sp for system/user mode)
4. Add writel/readl function in asm_io.h

CLI is worked on RTSM. Arndale is not supproted.

### CODE REVIEW

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/132/

**Comment by in1004kyu** [comment]
retest this please

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/133/

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/134/

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/135/

**Comment by in1004kyu** [comment]
retest this please

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/136/

**Pull request closed without merging**
