### PR TITLE
Added simple trap and emulation handler

### PR DESCRIPTION
**Pull request by Wonseok**
Added parse hsr for trapped instruction such as mcr, mrc, wfe, wfi, smc.
Added test code in bmguest.

TODO(wonseok): Adds other types of parser for trapped instruction.

### CODE REVIEW

**Comment by kesl** [comment]
Can one of the admins verify this patch?

**Comment by Wonseok** [comment]
Added simple trap and emulation handler #97

Added parse hsr for trapped instruction such as mcr, mrc, wfe, wfi, smc.
Added test code in bmguest.

TODO(wonseok): Adds other types of parser for trapped instruction.

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/31/

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/32/

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/33/

**Pull request closed without merging**
