### PR TITLE
Added comments and fixed address masking definition.

### PR DESCRIPTION
**Pull request by xiane**
Added comments - lpae.h, lpae.c, smp.h, mm.h, mm.c, vmm.h and vmm.c.
Fixed address masking definition. - lpae.c
TTBL_L1_OUTADDR_MASK    0x000000FFEC000000ULL -> 0x000000FFC0000000ULL
Added MMU_ON and MMU_OFF definition.
Change function name. - vmm.c
void vmm_stage2_enable -> static void stage2_mmu_enable

### CODE REVIEW

**Comment by kesl** [comment]
Can one of the admins verify this patch?

**Comment by xiane** [comment]
ok to test

**Comment by joohyun0115** [comment]
ok to test

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/190/

**Comment by joohyun0115** [comment]
very very good!

**Pull request merged**
