### PR TITLE
fixed ipa/pa table for supporting android on arndale board

### PR DESCRIPTION
**Pull request by kim6515516**

### CODE REVIEW

**Comment by kesl** [comment]
Can one of the admins verify this patch?

**Comment by Wonseok** [comment]
ok to test

Thanks,
Wonseok.

2014-09-01 14:03 GMT+09:00 kesl notifications@github.com:

**Comment by Wonseok** [comment]
s/fixed ipa/pa table for supporting android on arndale board0/[ARNDALE PATCH] Fixed stage 2 address translation table to support android

**Comment by joohyun0115** [comment]
ok to test

**Comment by Wonseok** [comment]
테스트는 통과됏는데 내가 수정하라고 한거 있어요 테스트 통과메일이 안오네 원래 안왔너요?

On Wednesday, September 3, 2014, joohyun0115 notifications@github.com
wrote:

> ok to test
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kesl/khypervisor/pull/219#issuecomment-54252960.

## 

Thanks,
Wonseok.

**Comment by joohyun0115** [comment]
ok to test

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/234/

**Pull request closed without merging**
