### PR TITLE
[ARNDALE PATCH]  : Supporting android on arndale board

### PR DESCRIPTION
**Pull request by kim6515516**
To do for supporting android.
1. Fixed stage 2 address translation table 
2. Added interrupt mapping table

### CODE REVIEW

**Comment by kesl** [comment]
Can one of the admins verify this patch?

**Comment by Wonseok** [comment]
ok to test

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/242/

**Comment by kesl** [comment]
CI : Test FAILed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/245/

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/246/

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/247/

**Pull request closed without merging**
