### PR TITLE
[versatile] Support versatile express

### PR DESCRIPTION
**Pull request by xiane**
Support versatile express

Fixed uart for work in versatile
Fixed makefile and linker script to build
Changed the core frequency to !Ghz
Create build script and u-boot command file for bmguest and linux guest
Fixed offset calculation for jumping to guest loader's coped point

### CODE REVIEW

**Comment by kesl** [comment]
Can one of the admins verify this patch?

**Comment by in1004kyu** [comment]
ok to test

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/264/

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/265/

**Pull request merged**
