### PR TITLE
Upgraded timer for supporting multiple timers.

### PR DESCRIPTION
**Pull request by Beomjun**
Changed timer's implementation and interface for supporting multiple timers.

Applied new timer interface on guest.c and vdev_timer.c and tests_gic_timer.c.

### CODE REVIEW

**Comment by kesl** [comment]
Can one of the admins verify this patch?

**Comment by Beomjun** [comment]
ok to test

**Comment by Wonseok** [comment]
Could you please change the title? It's not fit for your changed.

**Comment by joohyun0115** [comment]
ok to test

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/223/

**Comment by kesl** [comment]
CI : Test PASSed.
Refer to this link for build results: http://keslproject.iptime.org:8082/job/k-hypervisor_pull_request/224/

**Pull request merged**
